server:
  port: 2022

spring:
  datasource:
    url: jdbc:mysql://192.168.0.21:3306/justick
    username: justick_user
    password: 12345
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
