server:
  port: 2022

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/justick
    username: root
    password: 12345
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
